theme = "catppuccin_mocha_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
rulers = [100]
auto-save = true
true-color = true
popup-border = "all"
indent-heuristic = "tree-sitter"
jump-label-alphabet = "fjdkslaruvmeicwox"
default-line-ending = "lf"
end-of-line-diagnostics = "hint"
shell = ["fish", "-c"]

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.indent-guides]
render = true
character = "‚îÜ"
skip-levels = 1

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
A-F12 = ":open ~/.config/helix/languages.toml"
D = "delete_char_backward"
F11 = "merge_selections"
F12 = ":config-open"
F2 = "copy_between_registers"
F3 = [":fmt", ":wa"]
F4 = ":pipe sort"
A-F4 = ":pipe uniq"
X = "extend_line_above"
Y = ":yank-join"
[keys.normal.space]
Y = ":clipboard-yank-join"

[keys.select]
A-F12 = ":open ~/.config/helix/languages.toml"
D = "delete_char_backward"
F11 = "merge_selections"
F12 = ":config-open"
F2 = "copy_between_registers"
F3 = [":fmt", ":wa"]
F4 = ":pipe sort"
A-F4 = ":pipe uniq"
X = "extend_line_above"
Y = ":yank-join"
[keys.select.space]
Y = ":clipboard-yank-join"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "separator",
  "version-control",
  "separator",
  "read-only-indicator",
  "file-modification-indicator"
]
center = [ "spinner", "file-name", "spinner" ]
right = [
  "diagnostics",
  "selections",
  "register",
  "file-encoding",
  "separator",
  "position",
  "separator",
  "spacer",
  "position-percentage",
  "spacer"
]
mode.select = "‚ñë‚ñí‚ñìúµ∞ú¥êú∑•‚ñì‚ñí‚ñë"

mode.normal = "‚ñë‚ñí‚ñì‚ñåú∑Ü‚ñê‚ñì‚ñí‚ñë"

mode.insert = "‚ñë‚ñí‚ñìúµÆ‚†Äú∂™‚ñì‚ñí‚ñë"

